all: html

SPHINX_PROJECT_NAME = SOMANET EtherCAT Kit Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../sw_sncn_motorcontrol_ethercat_kit
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
