all: html

SPHINX_PROJECT_NAME = SOMANET EtherCAT Motor Control Slave Demo Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_slave_ethercat_motorcontrol
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
