all: html

SPHINX_PROJECT_NAME = EtherCAT Master Cyclic Positioning Control with Two Nodes Demo Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_master_cyclic_position_2_nodes
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
