all: html

SPHINX_PROJECT_NAME = SOMANET Cyclic Positioning Control with EtherCAT Demo Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_master_cyclic_position
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
