# This variable should contain a space separated list of all
# the directories containing buildable applications (usually
# prefixed with the app_ prefix)
#
# If the variable is set to "all" then all directories that start with app_
# are built.
BUILD_SUBDIRS = app_demo_master_cyclic app_demo_master_cyclic_position_2_nodes app_demo_master_cyclic_position_6_nodes app_demo_master_cyclic_torque app_demo_master_cyclic_torque_2_nodes app_demo_master_cyclic_velocity app_demo_master_cyclic_velocity_2_nodes app_demo_master_ethercat_tuning app_demo_master_object_dictionary app_demo_master_pdo_handling app_demo_slave_pdo_handling app_demo_slave_sdo_handling app_slave_ethercat_motorcontrol

XMOS_MAKE_PATH ?= ..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.toplevel
