/**
 * \file co_dictionary.c
 * \brief Main implementation of the CANopen object dictionary
 *
 * Copyright 2017 Synapticon GmbH <support@synapticon.com>
 *
 * WARNING: Do not edit by hand, this file is generated by
 * https://ecatcnf.synapticon.com
 */


#include "co_dictionary.h"

/*
 * Sizes of exported arrays
 */

const size_t entry_values_length           = 58;
const size_t entry_default_values_length   = 58;
const size_t entry_min_values_length       = 0;
const size_t entry_max_values_length       = 0;
const size_t string_length                 = 24;
const size_t object_entries_length         = 25;
const size_t object_dictionary_length      = 13;
const size_t bookmark_length               = 3;

struct _bookmarks bookmark[] = {
    { 0x1000, 0 },
    { 0x2000, 12 },
    { 0x3000, 23 },
    { 0x6660, 24 }
};

/*
 * Local storage of entry values.
 *
 * All entries are stored as byte slices within this array. The value pointer
 * in \c COD_Entry points to the LSB of the value within this memory area.
 */
uint8_t entry_values[entry_values_length] = {
    0x92, 0x01, 0x02, 0x00, /* 0x1000:0 Start: 0 */
    0x04,                   /* 0x1018:0 Start: 4 */
    0xd2, 0x22, 0x00, 0x00, /* 0x1018:1 Start: 5 */
    0x01, 0x02, 0x00, 0x00, /* 0x1018:2 Start: 9 */
    0x02, 0x00, 0x00, 0x0A, /* 0x1018:3 Start: 13 */
    0x00, 0x00, 0x00, 0x00, /* 0x1018:4 Start: 17 */
    0x01,                   /* 0x1600:0 Start: 21 */
    0x20, 0x00, 0x01, 0x20, /* 0x1600:1 Start: 22 */
    0x01,                   /* 0x1a00:0 Start: 26 */
    0x20, 0x00, 0x02, 0x20, /* 0x1a00:1 Start: 27 */
    0x04,                   /* 0x1c00:0 Start: 31 */
    0x00, 0x00, 0x03, 0x04, /* 0x1c00:1..4 */
    0x00,                   /* 0x1c10:0 Start: 36 */
    0x00,                   /* 0x1c11:0 Start: 37 */
    0x01,                   /* 0x1c12:0 Start: 38 */
    0x00, 0x16,             /* 0x1c12:1 Start: 39 */
    0x01,                   /* 0x1c13:0 Start: 41 */
    0x00, 0x1a,             /* 0x1c13:1 Start: 42 */
    0x00, 0x00, 0x00, 0x00, /* 0x2001:0 Start: 44 */
    0x00, 0x00, 0x00, 0x00, /* 0x2002:0 Start: 48 */
    0x00, 0x00, 0x00, 0x00, /* 0x3000:0 Start: 52 */
    0x00, 0x00              /* 0x6660:0 Start: 56 */
};

/*
 * Local storage of default values \see OD_Entry
 */
const uint8_t entry_default_values[entry_default_values_length] = {
    0x92, 0x01, 0x02, 0x00, /* 0x1000:0 Start: 0 */
    0x04,                   /* 0x1018:0 Start: 4 */
    0xd2, 0x22, 0x00, 0x00, /* 0x1018:1 Start: 5 */
    0x01, 0x02, 0x00, 0x00, /* 0x1018:2 Start: 9 */
    0x02, 0x00, 0x00, 0x0A, /* 0x1018:3 Start: 13 */
    0x00, 0x00, 0x00, 0x00, /* 0x1018:4 Start: 17 */
    0x01,                   /* 0x1600:0 Start: 21 */
    0x20, 0x00, 0x01, 0x20, /* 0x1600:1 Start: 22 */
    0x01,                   /* 0x1a00:0 Start: 26 */
    0x20, 0x00, 0x02, 0x20, /* 0x1a00:1 Start: 27 */
    0x04,                   /* 0x1c00:0 Start: 31 */
    0x00, 0x00, 0x03, 0x04, /* 0x1c00:1..4 */
    0x00,                   /* 0x1c10:0 Start: 36 */
    0x00,                   /* 0x1c11:0 Start: 37 */
    0x01,                   /* 0x1c12:0 Start: 38 */
    0x00, 0x16,             /* 0x1c12:1 Start: 39 */
    0x01,                   /* 0x1c13:0 Start: 41 */
    0x00, 0x1a,             /* 0x1c13:1 Start: 42 */
    0x00, 0x00, 0x00, 0x00, /* 0x2001:0 Start: 44 */
    0x00, 0x00, 0x00, 0x00, /* 0x2002:0 Start: 48 */
    0x00, 0x00, 0x00, 0x00, /* 0x3000:0 Start: 52 */
    0x00, 0x00              /* 0x6660:0 Start: 56 */
};

/*
 * Not every entry has a min and max value, to save some memory only the actual
 * necessary bytes for all available min and max values should be allocated.
 */
const uint8_t entry_min_values[entry_min_values_length];

const uint8_t entry_max_values[entry_max_values_length];

/*
 * This array contains all the strings found in the dictionary. Strings are
 * considered constant and not changeable by the master.
 *
 * TODO Make a second array for object names???
 */
const char *string[] = {
    "Device Type",        /* 0x1000 */
    "Identity",           /* 0x1018 */
    "Subindex 000",
    "Vendor ID",
    "Product Code",
    "Revision Number",
    "Serial Number",
    "SubIndex 000",       /* 7: SubIndex for mutliple objects */
    "Rx PDO Mapping",     /* 8: 0x1600 */
    "Test Output PDO",
    "Tx PDO Mapping",     /* 10: 0x1a00 */
    "Test Input PDO",
    "Sync Manager",       /* 12: 0x1c00 */
    "SyncMan 0",
    "SyncMan 1",
    "SyncMan 2",
    "SyncMan 3",
    "SM 0 Assingment",    /* 17: 0x1c10 */
    "SM 1 Assingment",    /* 18: 0x1c11 */
    "SM 2 Assingment",    /* 19: 0x1c12 */
    "SubIndex 1",         /* 20: SubIndex 1 - can be used by multiple objects */
    "SM 3 Assingment",    /* 21: 0x1c13 */
    "Command Object",     /* 22: 0x3000 */
    "Change Me Value"     /* 23: 0x6660 Testobject to change randomly */
};

COD_Entry object_entries[] = {
    {
        CODE_SET_ENTRY_INDEX(0x1000, 0, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[0]),
        &(entry_values[0]),
        &(entry_default_values[0]),
        NULL,
        NULL
    },
    {
        CODE_SET_ENTRY_INDEX(0x1018, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[2]),
        &(entry_values[4]),
        &(entry_default_values[4]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1018, 1, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[3]),
        &(entry_values[5]),
        &(entry_default_values[5]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1018, 2, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[4]),
        &(entry_values[9]),
        &(entry_default_values[9]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1018, 3, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[5]),
        &(entry_values[13]),
        &(entry_default_values[13]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1018, 4, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[6]),
        &(entry_values[17]),
        &(entry_default_values[17]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1600, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[5]),
        &(entry_values[21]),
        &(entry_default_values[21]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1600, 1, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[5]),
        &(entry_values[22]),
        &(entry_default_values[22]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1a00, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[5]),
        &(entry_values[26]),
        &(entry_default_values[26]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1a00, 1, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[5]),
        &(entry_values[27]),
        &(entry_default_values[27]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c00, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[7]),
        &(entry_values[31]),
        &(entry_default_values[31]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c00, 1, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[13]),
        &(entry_values[32]),
        &(entry_default_values[32]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c00, 2, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[14]),
        &(entry_values[33]),
        &(entry_default_values[33]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c00, 3, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[15]),
        &(entry_values[34]),
        &(entry_default_values[34]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c00, 4, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[16]),
        &(entry_values[35]),
        &(entry_default_values[35]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c10, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[7]),
        &(entry_values[36]),
        &(entry_default_values[36]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c11, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[7]),
        &(entry_values[37]),
        &(entry_default_values[37]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c12, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[7]),
        &(entry_values[38]),
        &(entry_default_values[38]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c12, 1, 0),
        DEFTYPE_UNSIGNED16,
        16,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[20]),
        &(entry_values[39]),
        &(entry_default_values[39]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c13, 0, 0),
        DEFTYPE_UNSIGNED8,
        8,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[7]),
        &(entry_values[41]),
        &(entry_default_values[41]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x1c13, 1, 0),
        DEFTYPE_UNSIGNED16,
        16,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[20]),
        &(entry_values[42]),
        &(entry_default_values[42]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x2001, 0, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, ACCESS_TXPDO_MAP, ACCESS_ALL_RD),
        0,
        &(string[11]),
        &(entry_values[44]),
        &(entry_default_values[44]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x2002, 0, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, ACCESS_RXPDO_MAP, ACCESS_ALL_RDWR),
        0,
        &(string[9]),
        &(entry_values[48]),
        &(entry_default_values[48]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x3000, 0, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RDWR),
        0,
        &(string[22]),
        &(entry_values[52]),
        &(entry_default_values[52]),
        NULL,
        NULL
    }, {
        CODE_SET_ENTRY_INDEX(0x6660, 0, 0),
        DEFTYPE_UNSIGNED32,
        32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RDWR),
        0,
        &(string[23]),
        &(entry_values[56]),
        &(entry_default_values[56]),
        NULL,
        NULL
    }
};

COD_Object object_dictionary[] = {
    {
        0x1000,
        OBJECT_TYPE_VAR,
        DEFTYPE_UNSIGNED32,
        ACCESS_ALL_RD,
        0,
        &(string[0]),
        &(object_entries[0])
    },
    {
        0x1018,
        OBJECT_TYPE_RECORD,
        DEFSTRUCT_PDO_MAPPING,
        ACCESS_ALL_RD,
        4,                          /* max subindex */
        &(string[1]),
        &(object_entries[1])
    }, {
        0x1600, /* RxPDO: Output: Master->Slave */
        OBJECT_TYPE_RECORD,
        DEFSTRUCT_PDO_MAPPING,
        ACCESS_ALL_RD,
        1,
        &(string[8]),
        &(object_entries[6])
    }, {
        0x1A00, /* TxPDO: Input: Slave-> Master */
        OBJECT_TYPE_RECORD,
        DEFSTRUCT_PDO_MAPPING,
        ACCESS_ALL_RD,
        1,
        &(string[10]),
        &(object_entries[8]) /* previous object + number of entries of previous object */
    }, {
        0x1C00,
        OBJECT_TYPE_ARRAY,
        DEFTYPE_UNSIGNED8,
        ACCESS_ALL_RD,
        4,
        &(string[12]),
        &(object_entries[10])
    }, {
        0x1C10,
        OBJECT_TYPE_ARRAY,
        DEFTYPE_UNSIGNED16,
        ACCESS_ALL_RD,
        0,
        &(string[17]),
        &(object_entries[15])
    }, {
        0x1C11,
        OBJECT_TYPE_ARRAY,
        DEFTYPE_UNSIGNED16,
        ACCESS_ALL_RD,
        0,
        &(string[18]),
        &(object_entries[16])
    }, {
        0x1C12,
        OBJECT_TYPE_ARRAY,
        DEFTYPE_UNSIGNED16,
        ACCESS_ALL_RD,
        1,
        &(string[19]),
        &(object_entries[17])
    }, {
        0x1C13,
        OBJECT_TYPE_ARRAY,
        DEFTYPE_UNSIGNED16,
        ACCESS_ALL_RD,
        1,
        &(string[21]),
        &(object_entries[19])
    }, {
        0x2001,
        OBJECT_TYPE_VAR,
        DEFTYPE_UNSIGNED32,
        ACCESS_SET_FLAGS(0, 0, ACCESS_TXPDO_MAP, ACCESS_ALL_RD),
        0,
        &(string[11]),
        &(object_entries[21])
    }, {
        0x2002,
        OBJECT_TYPE_VAR,
        DEFTYPE_UNSIGNED32,
        ACCESS_SET_FLAGS(0, 0, ACCESS_RXPDO_MAP, ACCESS_ALL_RD),
        0,
        &(string[9]),
        &(object_entries[22])
    }, {
        0x3000,
        OBJECT_TYPE_VAR,
        DEFTYPE_UNSIGNED32,
        ACCESS_SET_FLAGS(0, 0, 0, ACCESS_ALL_RD),
        0,
        &(string[22]),
        &(object_entries[23])
    }, {
        0x6660,
        OBJECT_TYPE_VAR,
        DEFTYPE_UNSIGNED16,
        ACCESS_ALL_RD,
        0,
        &(string[23]),
        &(object_entries[24])
    }
};
